# Generated by Django 6.0.3 on 2026-03-13 21:56

import apps.transactions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_profile_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aura', models.IntegerField(validators=[apps.transactions.models.validator_is_zero], verbose_name='Aura')),
                ('reason', models.CharField(max_length=255, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='users.profile', verbose_name='Recipient')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to='users.profile', verbose_name='Sender')),
            ],
        ),
    ]
